### ISSUE TITLE
No channel starts playing after 2.1.0 update

### ISSUE THREAD

**Issue by kruska7** [euzu/m3u-filter#149]
No channel starts playing after updating from 2.0.10 to 2.1.0, without any changes in configuration. Using xtream redirect. There is no error or similar in log to point to what's going wrong. Everything was working fine on previous version 2.0.10.

Config:

```
api: {host: ***, port: ***}
working_dir: ./data
schedules:
- schedule: "0  45  7,12,15,19,21,23  *  *  *  *"
  targets:
  - mytarget
update_on_boot: true
web_ui_enabled: false
```

Api proxy:

```
server:
- name: default
  protocol: http
  host: ***
  http_port: '***'
  timezone: Europe/Berlin
  message: Welcome to m3u-filter
user:
- target: mytarget
  credentials:
  - username: ***
    password: ***
    proxy: redirect
    server: default
```

Source:

```
templates:
- name: QUALITY
  value: Name ~ ".* (4K|RAW|ᵁᴴᴰ|ᴿᴬᵂ).*"
- name: QUALITY_BLACKLIST
  value: Name ~ ".* (SD|ˢᴰ|HD|ᴴᴰ|480p|⁴⁸⁰ᵖ|576p|⁵⁷⁶ᵖ|720p|⁷²⁰ᵖ).*"
- name: GROUP_SE
  value: Group ~ "^SE.*"
- name: GROUP_UK
  value: Group ~ "^UK.*"
- name: GROUP_US
  value: Group ~ "^US.*"
- name: ALL_GROUPS
  value: >-
    (!GROUP_SE! OR !GROUP_UK! OR !GROUP_US!) AND NOT
    !QUALITY_BLACKLIST!
sources:
- inputs:
    - name: my_provider
      type: xtream
      headers:
        User-Agent: "Mozilla/5.0 (AppleTV; U; CPU OS 14_2 like Mac OS X; en-us) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15"
        Accept: application/json
        Accept-Encoding: gzip
      url: 'http://***'
      epg_url: 'http://***'
      username: ***
      password: ***
      options: {xtream_skip_vod: true, xtream_skip_series: true}
  targets:
    - name: mytarget
      output:
        - type: xtream
      filter: "!ALL_GROUPS!"
      options: {ignore_logo: true, xtream_skip_live_direct_source: false, xtream_skip_video_direct_source: false, xtream_skip_series_direct_source: false}
```

**Comment by euzu** [comment]
@kruska7 i see in your config you are using redirect, redirect has not changed, because it does only a redirect to the provider.

The db files have been changed.  But i see you have `update_on_boot: true`. Your files should be  fine.

I try to use your config to test  with 2.1.0. 

Btw i am using 2.10 and have no problems.

For test purposes, you could stop m3u-filter,   backup the data folder,  and start m3u-filter to see if it works again.

What for a client are you using ?

**Comment by kruska7** [comment]
I tried wiping data folder before trying again, but that didn't help. The channels just won't start to play.

Rolling back to 2.0.10 and channels starts playing fine again.

I'm using UHF: https://www.uhfapp.com/

**Comment by euzu** [comment]
@kruska7  i have tested with your config and found the bug.  I will fix it and deploy a new release.

**Comment by euzu** [comment]
@kruska7  i have released a image v2.1.1. This should fix your problem. If it does please close this issue.

**Comment by kruska7** [comment]
@euzu Issue is back after v2.1.2. No channel plays, same config and app used as previously.

Rolling back to v2.1.1 and it works fina again.

**Comment by euzu** [comment]
@kruska7 any log outputs? Did you run an update and updated playlist in player?

**Comment by euzu** [comment]
@kruska7 i found the problem, i forgot to merge the code for stream api to the release. Now i have included it. Will deploy a new release now.

**Comment by kruska7** [comment]
Works again 👍
