### ISSUE TITLE
Allow regex transformations in rename

### ISSUE THREAD

**Issue by pletexier** [euzu/m3u-filter#88]
Please allow transformations in the new_name statement like \U to transform a channel name in uppercase.

**Comment by euzu** [comment]
@pletexier this is not possible, I have implemented a feature which could fit your needs.

`transform`

`transform` is a list of transformations.

Each transformation can have the following attributes:
- `field` _mandatory_ the field where the transformation will be applied
- `modifier` _mandatory_, values are: `lowercase`, `uppercase` and `capitalize`
- `pattern` _optional_  is a regular expression (not filter!) with captures. Only needed when you want to transform parts of the property.

For example: first 3 chars of channel name to lowercase: 

```yaml
      mapper:
        - pattern: 'Group ~ ".*"'
          transform:
          - field: name
            pattern: "^(...)"
            modifier: lowercase
```

channel name to uppercase:

```yaml
      mapper:
        - pattern: 'Group ~ ".*"'
          transform:
          - field: name
            modifier: uppercase
```

**Comment by euzu** [comment]
@pletexier is this solved for you ?

**Comment by pletexier** [comment]
Hello @euzu,
Thanks for your reply, and sorry for the response delay.

I have tried the "channel to uppercase" example, and it seems it does not work...
I still have some channels with lowercase.

Regards,

Patrice

**Comment by euzu** [comment]
@pletexier if you have an example i can test it. I have tested it successfully.

**Comment by pletexier** [comment]
Hello, you're right. I have upgraded to latest version and it's working now.
Regards,
Patrice
